"""Validation hygiene checks for reviewer handoff.

The project has many validation scripts. This module checks that the canonical
validation flow does not leave generated Python bytecode/cache artifacts behind
and that the clean validation path is visible to reviewers. It is a static
source-package check; it does not start packet capture, send packets, scan a
network, or prove real IPv6 detection capability.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

CURRENT_VERSION = "27.0.0-safe"
CURRENT_RELEASE_NOTE = "RELEASE_NOTES_v27.md"

REQUIRED_FILES = {
    "scripts/clean_release_artifacts.py",
    "scripts/validate_project.py",
    "scripts/run_clean_validation.py",
    "scripts/final_handoff_check.py",
    "services/process_control.py",
    "docs/quality/VALIDATION_HYGIENE.md",
    CURRENT_RELEASE_NOTE,
}

REQUIRED_VALIDATE_TOKENS = (
    "cleanup_generated_artifacts",
    "sys.dont_write_bytecode = True",
    "finally:",
    "TemporaryDirectory",
    "isolated_subprocess_kwargs",
    "terminate_process_tree",
    "proc.wait(timeout=timeout_seconds)",
)

REQUIRED_RUNNER_TOKENS = (
    "PYTHONDONTWRITEBYTECODE",
    "clean_release_artifacts.py",
    "validate_project.py",
)

REQUIRED_HANDOFF_TOKENS = (
    "clean_workspace_before",
    "clean_workspace_after",
    "PYTHONDONTWRITEBYTECODE",
)


@dataclass(frozen=True)
class ValidationHygieneCheck:
    name: str
    ok: bool
    detail: Any

    def to_dict(self) -> dict[str, Any]:
        return {"name": self.name, "ok": self.ok, "detail": self.detail}


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except FileNotFoundError:
        return ""


def _missing_tokens(text: str, tokens: tuple[str, ...]) -> list[str]:
    return [token for token in tokens if token not in text]


def run_validation_hygiene_check(*, app_root: Path, app_version: str) -> dict[str, Any]:
    validate_project = _read(app_root / "scripts" / "validate_project.py")
    clean_runner = _read(app_root / "scripts" / "run_clean_validation.py")
    handoff = _read(app_root / "scripts" / "final_handoff_check.py")
    cleaner = _read(app_root / "scripts" / "clean_release_artifacts.py")
    readme = _read(app_root / "README.md")
    doc = _read(app_root / "docs" / "quality" / "VALIDATION_HYGIENE.md")

    missing_files = sorted(path for path in REQUIRED_FILES if not (app_root / path).exists())

    checks = [
        ValidationHygieneCheck(
            "validation_version_matches_app",
            app_version == CURRENT_VERSION,
            {"app_version": app_version, "expected": CURRENT_VERSION},
        ),
        ValidationHygieneCheck(
            "validation_hygiene_files_present",
            not missing_files,
            {"missing": missing_files},
        ),
        ValidationHygieneCheck(
            "validate_project_cleans_generated_artifacts",
            not _missing_tokens(validate_project, REQUIRED_VALIDATE_TOKENS),
            {"missing_tokens": _missing_tokens(validate_project, REQUIRED_VALIDATE_TOKENS)},
        ),
        ValidationHygieneCheck(
            "clean_validation_runner_is_bytecode_safe",
            not _missing_tokens(clean_runner, REQUIRED_RUNNER_TOKENS),
            {"missing_tokens": _missing_tokens(clean_runner, REQUIRED_RUNNER_TOKENS)},
        ),
        ValidationHygieneCheck(
            "final_handoff_cleans_before_and_after",
            not _missing_tokens(handoff, REQUIRED_HANDOFF_TOKENS),
            {"missing_tokens": _missing_tokens(handoff, REQUIRED_HANDOFF_TOKENS)},
        ),
        ValidationHygieneCheck(
            "cleaner_targets_validation_cache_artifacts",
            all(token in cleaner for token in ("__pycache__", ".pytest_cache", ".pyc", ".pyo")),
            "clean_release_artifacts.py should know about Python/test cache artifacts generated by validation.",
        ),
        ValidationHygieneCheck(
            "validation_hygiene_is_documented",
            all(token in (readme + doc).lower() for token in ("run_clean_validation.py", "validation_hygiene", "simulation")),
            "README and VALIDATION_HYGIENE should describe the clean validation path and simulator boundary.",
        ),
    ]
    items = [check.to_dict() for check in checks]
    failures = [item for item in items if not item["ok"]]
    return {
        "status": "pass" if not failures else "fail",
        "version": CURRENT_VERSION,
        "mode": "safe_simulation",
        "summary": {"total": len(items), "passed": len(items) - len(failures), "failures": len(failures)},
        "checks": items,
        "notes": [
            "This gate checks validation workspace hygiene only.",
            "It does not add live IPv6 monitoring, packet capture, packet sending, or network scanning.",
        ],
    }
